### ISSUE TITLE
«Trust» button on certificate dialog seems broken

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#107]
Going to gemini://mozz.us/journal/2021-01-01.gmi, lagrange tells me the certificate changed.
It also tells me the trusted certificate was about to expire, which is useful information!

I click on the warning and get the certificate status dialog. I chose to trust the new certificate and click the trust button. It seems to do nothing, the warning is still there, event if I reload the page.

**Comment by skyjake** [comment]
The expected behavior is that after clicking Trust and then reloading, the warnings go away as the new trusted certificate comes into effect. At least it has been working for me this way, although certificate changes occur pretty seldom so I haven't done this more than a few times thus far.

I'll need to run a test server where I can change the certificates manually and see if I can reproduce the issue.

**Comment by skyjake** [comment]
Did you have multiple tabs open when you pressed Trust? Looks like that has been one possible problem here.

**Comment by MCMic** [comment]
Yes I always have a lot of tabs opened.

**Comment by MCMic** [comment]
Clicking Trust should also hide the warning right away to make it clear that it worked.

**Comment by skyjake** [comment]
> Clicking Trust should also hide the warning right away to make it clear that it worked.

Done.

These changes should now have addressed the problem.

**Comment by skyjake** [comment]
Included in v1.0.2.
