### ISSUE TITLE
Show full URLs on link lines

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#126]
Currently all you can see in advance is the hostname, which is okay for Gemini links as of now (everyone tends to have their own hostname), but not so much for HTTP links where lots of people share a host such as blogspot.com.  As Gemini grows and there are more shared hosting providers, this feature will become more important.

**Comment by skyjake** [comment]
Full URLs can be quite long, which is why they are not shown over the link lines.

The recently released version 1.1 introduced this feature:
<img width="849" alt="Screen Shot 2021-01-31 at 7 35 18" src="https://user-images.githubusercontent.com/1225742/106375703-134da800-6397-11eb-8abd-5541db45a4e4.png">

It can be enabled via Preferences (General > Show URL on hover). I believe this addresses the issue?
