### ISSUE TITLE
Links on a page to a page with the same URL are not followed when clicked

### ISSUE THREAD

**Issue by Packbat** [skyjake/lagrange#129]
A bit of an unusual problem, but it looks like there's a feature in Lagrange, I presume to save data and reduce network requests, that prevents the browser from reloading a link when that link points to the current page. Unfortunately, at least one Geminispace game uses URLs to represent actions within the game, and so performing the same action twice in a row requires loading the same URL twice in a row.

This can be worked around by reloading the page instead of following the link, but it was a source of confusion and makes playing the game as normal more difficult. Something like a separate "this link goes to the current page" symbol would allow the same saving of data while not breaking Geminispace games that use URLs this way.

**Comment by Br0000k** [comment]
Could you give me an example of a Geminispace game that does this please? I might be able to do a fix.

**Comment by Packbat** [comment]
gemini://alchemi.dev/maze/ is the one I was playing.

**Comment by skyjake** [comment]
I think this is because at some point in early development of Lagrange, I had to prevent reloading of the page due to some UI event where the URL wasn't changing but the navbar still triggered an "open" command.

Now I think this safeguard is obsolete, so I'll make it so that any page can be reloaded by clicking on links or bookmarks, retyping the URL and pressing Enter, etc.

**Comment by skyjake** [comment]
Providing this doesn't have side effects that weren't immediately obvious, I'll include the change in v1.1.1 as a bugfix.
