### ISSUE TITLE
localhost not recognized (at least on Mac)

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#14]
Whatever you are using to convert hostnames to IP addresses looks in DNS only, and does not respect `/etc/hosts`.  This means that `localhost` cannot be used.  This is particularly bad when specifying local proxies, which have to be given as `127.0.0.1:1965` (or some other port) rather than the usual `localhost:1965`.

To reproduce, run a local Gemini server and type `gemini://localhost/blah/blah` into the URL bar.  Alternatively,  run Agena locally, set the gopher_proxy to `localhost:1965`, and type `gopher://gopher.floodgap.com` into the URL bar.  Both tests will pass if you use `127.0.0.1` instead.

To fix, use standard Posix `getaddrinfo()` instead of talking to DNS directly.  If this is not feasible for some reason, load and cache `/etc/hosts` and use it before going to DNS.  The format is trivial, but multiple host names can appear on a single line: see `man 5 hosts` for details.  If this is not feasible either, special-case `localhosts` directly in the code.

This interacts with #13 to give no outward sign of what is failing or why.

**Comment by skyjake** [comment]
> To fix, use standard Posix getaddrinfo() instead of talking to DNS directly. 

I am using getaddrinfo, see [address.c](https://git.skyjake.fi/skyjake/the_Foundation/src/branch/master/src/platform/posix/address.c#L73).

I'll run some tests to see if this actually gets called for localhost addresses as it should.

**Comment by skyjake** [comment]
Did some debugging. When I'm calling `getaddrinfo()`, it is not specified whether the address should be IPv4 or IPv6 so it returns both. The first returned address is used for connecting, so it tries ::1 instead of 127.0.0.1, which results in a "connection refused" error from the socket.

Connection and TLS errors in general are not properly reported in the UI at the moment.

I suppose it is safe to default to IPv4 in the case of "localhost" at least.

**Comment by skyjake** [comment]
Made some [improvements to socket connect](https://git.skyjake.fi/skyjake/the_Foundation/commit/7ccfb006fe485b0076c99c1749514ba3781676af). The dev branch uses the improved version.

At least it now Works For Me™.
