### ISSUE TITLE
Option to disable font smoothing

### ISSUE THREAD

**Issue by denizzzka** [skyjake/lagrange#150]
For many years I have been using disabling of font smoothing because I find this comfortable for eyes when using monitor for a long time. I also know that I am not alone. My wish: please use system settings of this mode.

This is what I mean: left image is from Lagrange and right is from Google Chrome
![lagrange_complain](https://user-images.githubusercontent.com/974632/107312700-92dc2500-6ac3-11eb-8a57-c0b5054837e2.png)

**Comment by skyjake** [comment]
While it isn't trivial to check an OS setting for this — Lagrange aims to be minimal and platform-agnostic — I can add a manual setting for disabling font smoothing in Preferences.

There is a downside, though. Since the font renderer is also not dependent on any system libraries, it is somewhat limited. One of the limitations is lack of hinting, which means that glyph shapes will not be aligned with the pixel grid in an optimal way. The end result is that without smoothing the glyph shapes may look less correct.

**Comment by skyjake** [comment]
@denizzzka I did some experiments. Here is option 1: reduced smoothing.
<img width="445" alt="sm1" src="https://user-images.githubusercontent.com/1225742/109540823-af202000-7acb-11eb-936a-3f0eb5ae0dca.png">

And option 2: no smoothing at all.
<img width="429" alt="sm2" src="https://user-images.githubusercontent.com/1225742/109540850-b6dfc480-7acb-11eb-99e9-298cc9d19eb4.png">

What do you think? Personally I think option 1 greatly reduces the blurriness while still keeps the glyph shapes somewhat correct. Option 2 gets a little too jagged in my estimation...

**Comment by antonioprates** [comment]
I know this was not my request, but if it's just a boolean flag, I would rather have option 2: no smoothing at all. It would work for my personal preference (i don't mind it looks a bit jagged). But if you can add both as options, that would be great.

**Comment by denizzzka** [comment]
@skyjake I prefer option 2

**Comment by skyjake** [comment]
v1.8 will have a "Font smoothing" toggle in Preferences > Fonts. It applies to all text in the UI and page content.

I'll consider adding a way to adjust the amount of smoothing reduction, perhaps via a command line option.

**Comment by skyjake** [comment]
v1.8 has been released.
