### ISSUE TITLE
Search engines queries via the navbar

### ISSUE THREAD

**Issue by tteeoo** [skyjake/lagrange#157]
It would be nice to add another bar to the top of the interface (or perhaps integrate it into the current URL bar) for search engines.
I had something in mind like Firefox's old search bar, smaller and to the right of the URL bar.
You would be able to configure a search engine (just a URL that resolves to an input, like gemini://gus.guru), and whatever you type in to the bar would be sent to it as input, taking you to the resulting page, as if you entered the search engine's URL into the URL bar manually and typed something in.

**Comment by skyjake** [comment]
I agree an integrated search of some sort would be nice. I was planning to try adding it in the URL input field / quick search.

If the window is large enough there certainly would be room for a separate input field, though.

**Comment by bortzmeyer** [comment]
I disagree with the whole idea. Confusing the address bar and a search bar is evil because it gives too much power to the search engine, obscuring the URI (which is a crucial information for the user), and making people believe they need to go through a search engine. Google does it in Chrome, it does not mean it should be copied.

**Comment by tteeoo** [comment]
Correct me if I'm wrong @skyjake, but your user experience wouldn't change. You can still type URLs as normal, and it probably wouldn't be difficult to implement a way to disable it altogether in the config. It also wouldn't obscure anything until you start typing in the input again (just as typing in a URL would), because the URL gets filled in again when you visit a page.

Also, I get that search isn't as important to Gemini as it is to the Web, but I didn't suggest this feature to copy anything from Chrome. I suggested it because I thought it would be legitimately useful. How does this make people believe that they need to search? It just makes it easier if they already want to.

**Comment by skyjake** [comment]
@bortzmeyer I understand your concern. The browser should not be dictating search engine usage, and definitely there should be no confusion as to what happens when typing in the address bar.

And yes @tteeoo, the way this will work can be summarized as: everything works the same as before, except that if you type text that is not an URL and press Enter, it will load up the user's configured search URL with the given text as a query string. The user has to opt in to this by first setting up the search URL manually. I will also add an indicator in the address bar that makes it clear what will happen when pressing Enter (page load or search query).
