### ISSUE TITLE
Non-Gemini redirects fail instead of being reprocesed through proxies

### ISSUE THREAD

**Issue by johnwcowan** [skyjake/lagrange#16]
When using `duckling-proxy` to access an HTTP site, and the site redirects you to another HTTP URL (as is very common), Lagrange doesn't follow it.

To reproduce: type `http://www.unsyntax.org/` into the URL bar.  This URL gets redirected to `https://www.unsyntax.org` silently, as is desirable.  Lagrange will present an error page.

To fix: Make sure that URLs are uniformly processed, whether they come from a request or a redirect.

**Comment by skyjake** [comment]
I think this is more of a user experience issue, since the page that Lagrange presents is meant to allow one to manually follow the redirect if appropriate.

It would be nicer if this warning would appear when the redirect changes the scheme instead of whenever it is a non-gemini one. That would allow http → https redirects automatically (assuming http and https are considered equivalent).
