### ISSUE TITLE
Desktop window shadows disappear under KDE

### ISSUE THREAD

**Issue by yannicka** [skyjake/lagrange#160]
When I start Lagrange, the shadows of all my windows disappear under KDE.

Here is an example with and without Lagrange (also, you can see that the rounded edges are no longer rounded):

![Screenshot_20210214_140939](https://user-images.githubusercontent.com/22885898/107877747-8cd4b280-6ece-11eb-8ca2-4d349939b041.png)

![Screenshot_20210214_140928](https://user-images.githubusercontent.com/22885898/107877751-8fcfa300-6ece-11eb-822a-fb135890e3cc.png)

I don't know if Lagrange is responsible for the problem, or how to fix it, but it's the only application that does that on my system.

Operating System: Debian GNU/Linux
KDE Plasma Version: 5.20.5
KDE Frameworks Version: 5.78.0
Qt Version: 5.15.2

On one of the last commits of Lagrange.

**Comment by skyjake** [comment]
Here is another KDE graphics glitch report, perhaps related: #137 

Lagrange uses the [SDL library](https://libsdl.org/) to manage its window and graphics. Maybe it has some sort of a conflict with the KDE desktop compositor?

I rarely use KDE myself, but I could investigate if workarounds are available using a VM.

**Comment by yannicka** [comment]
Yes I think there is a conflict or something like that, a parameter to add, but I'm not sure what to do to identify the cause of the problem, I don't master these subjects (C, SDL, compositor...).

**Comment by zacryol** [comment]
It looks like opening Lagrange completely disables the KDE compositor while it's running, based on my recent experience.
I was using the version on Flathub if that makes a difference.

**Comment by skyjake** [comment]
I found a workaround for this. The problem happens because the KWin compositor allows applications to request blocking compositing for performance reasons (e.g., games), and apparently whatever SDL is doing will cause that to happen.

You have two options: disallow all applications from blocking compositing, or disallow only Lagrange from blocking it.

The former option is found in _System Settings > Display and Monitor > Compositor > Allow applications to block compositing_.

The latter option is done by right-clicking on the Lagrange window title bar and selecting _More Actions_ > _Configure Special Application Settings..._ > _Appearance & Fixes > Block compositing_: set to "Force" and "No".

Closing the issue as this falls outside Lagrange's scope.

**Comment by dquark** [comment]
> The former option is found in _System Settings > Display and Monitor > Compositor > Allow applications to block compositing_.

This is not recommended since it can hurt performance in certain applications like games. Second solution is much better.

**Comment by Nexion** [comment]
@skyjake I guess this is more than just KDE related issue. I'm using a tiling WM with [picom](https://github.com/yshui/picom) compositor. If a Lagrange window is active, all the compositor settings (e.g. window transparency) disappear. If it's minimized in taskbar or another workspace is active, the compositor is working as usual.

**Comment by hikmet517** [comment]
Adding `SDL_SetHint(SDL_HINT_VIDEO_X11_NET_WM_BYPASS_COMPOSITOR, "0");` in main.c solves this issue.

**Comment by skyjake** [comment]
Many thanks! I hadn't noticed there's an SDL hint for this.
