### ISSUE TITLE
Image not displayed (hardware accelerated rendering)

### ISSUE THREAD

**Issue by bortzmeyer** [skyjake/lagrange#167]
lagrange 1.1.3, gcc 8.3.0 on Debian.

Everything is fine except that inline image at  gemini://gemeaux.bortzmeyer.org/ (link "Une jolie image") is not displayed. When I select "View image", I just get an empty black space.

I see in the logs of the server that the image is fetched successfully (status code 20). 

I can display images on other capsules but I do not see why this specific image fails. Lagrange does not display an error message.

**Comment by smaragdus** [comment]
@bortzmeyer 

I checked this particular image (`gemini://gemeaux.bortzmeyer.org/valleuse-antifer.jpg`) and the Windows version of Lagrange displayed it just right, screen:

![Lagrange 1 1 3 - 2021-02-17 - 002](https://user-images.githubusercontent.com/9025757/108246853-9a05d180-715a-11eb-861a-3877777d46a8.png)

Currently I don't have Linux installed so I cannot test the Linux version of Lagrange.

**Comment by skyjake** [comment]
@bortzmeyer My guess is that since this is a rather large image, copying it to an OpenGL texture for rendering failed for memory/texture max size/etc. reasons.

Any difference when running with the `--sw` command line option?

The image viewer currently doesn't try to resize images for viewing. More appropriate behavior would be for Lagrange to scale them down to the known valid maximum texture size, and also down to the size of the window if it happens to be smaller.

**Comment by bortzmeyer** [comment]
> I checked this particular image (`gemini://gemeaux.bortzmeyer.org/valleuse-antifer.jpg`) and the Windows version of Lagrange displayed it just right, screen:

I was talking about inline display (using `gemini://gemeaux.bortzmeyer.org/` and  then asking Lagrange to display inline).

**Comment by bortzmeyer** [comment]
> @bortzmeyer My guess is that since this is a rather large image, copying it to an OpenGL texture for rendering failed for memory/texture max size/etc. reasons.

It worked on another Debian machine, with more memory, so, yes, it could be size-related. 

But an error message "Out of memory for this huge image" could be a good idea.

**Comment by bortzmeyer** [comment]
> Any difference when running with the `--sw` command line option?

Yes, it works, I see the image.
