### ISSUE TITLE
Assertion failure when accessing non-Gemini servers with Gemini scheme

### ISSUE THREAD

**Issue by Br0000k** [skyjake/lagrange#181]
When lagrange accesses a non-Gemini server (such as HTTPS) with a Gemini scheme, it crashes. Reproducing the bug just involves starting a HTTPS (or similar) server and attempting to connect to it with gemini://

`lagrange: /home/brook/lagrange/src/gmrequest.c:232: readIncoming_GmRequest_: Assertion 'd->state != finished_GmRequestState' failed.`
`Aborted (core dumped)`

Hopefully I might be able to figure out a bug fix tommorow.

**Comment by skyjake** [comment]
This is a debug assertion that occurs when a TlsRequest has already finished when an update notification is being sent. In a release build this doesn't seem to crash (for me at least).

It should be safe to cancel the update notification in this case, since the request was probably terminated early due to an error.
