### ISSUE TITLE
support of webp and mozjpeg images

### ISSUE THREAD

**Issue by zorglubu** [skyjake/lagrange#206]
Hello,

It would be nice to have lagrange supporting light formats of images like webp and mozjpeg.

Anyway, thanks a lot for the work already done in lagrange :-)

**Comment by skyjake** [comment]
I'm hesitant to add new dependencies for somewhat rare data formats...

One possible approach would be to add a build option to use [SDL_image](https://www.libsdl.org/projects/SDL_image/) to handle image loading, since that would contain the various image library dependencies. That would take care of WEBP at least.

**Comment by t-900-a** [comment]
Might as well go with avif/av1, which is the successor to webp

**Comment by Strahinja** [comment]
If not adding a build option to use SDL_image to display images inside Lagrange, can you at least add opening using an external tool in the case of unsupported formats? Something like `xdg-open <filename>`?

**Comment by skyjake** [comment]
Yes, using external tools is a good compromise for this. There is the older issue #135 covering that.

**Comment by CyberTailor** [comment]
webp support has been added in v1.7.0

**Comment by skyjake** [comment]
I took a look at mozjpeg and it seems to be an encoder that produces standard JPEGs. So decompressing JPEGs created with it should already be working. Let me know if this is not the case...
