### ISSUE TITLE
Dialog keyboard navigation (add 'Save Bookmark' to tab cycling in "Add Bookmark" dialog)

### ISSUE THREAD

**Issue by GiovanniMoretti** [skyjake/lagrange#231]
Currently, the Tab key cycles through the Title/URL/Tags/Icon fields - using the mouse is necessary to do the save.

Suggestions: in the "Add Bookmark" dialog:

- Add "Save" and then "Cancel" to the tab cycling; in that order as most of the time Save is probably the wanted option.
- Make Esc cancel the dialog immediately (as usual). Not sure why but currently two presses are required.

**Comment by skyjake** [comment]
I agree the UX is a bit questionable here. The Save button actually does have a keyboard shortcut: Ctrl+Return on Windows/Linux, and ⌘⏎ on the Mac. I'll consider making the shortcut visible in the button for clarity.

The double Esc is happening because the first Esc clears the input focus, while the second one actually cancels the dialog. It would make more sense to dismiss the whole dialog on the first Esc.

Keyboard-navigable UI focus, e.g., allowing the input focus to move onto buttons, is a larger topic that needs to be considered in the scope of the entire app UI. (There's also #144.)

**Comment by skyjake** [comment]
Focus cycling to dialog buttons has been implemented.
