### ISSUE TITLE
Export client certificate

### ISSUE THREAD

**Issue by ancarda** [skyjake/lagrange#236]
If I generate a client certificate under Identity > New Identity... I can then use it, but I can't seem to export it anywhere. I have several computers and would like to use the same cert for gemini://feeds.drewdevault.com/ on several machines.

Is there any way to do this other than generating the certificate outside Lagrange (i.e. with OpenSSL) and then importing it?

**Comment by skyjake** [comment]
Lagrange's certificates are stored as .crt and .key files in ~/.config/lagrange/idents/ (or equivalent for your platform). The files are named using the certificate fingerprint. To "export", just copy the files where you need them.

Adding a user-friendly export feature would be nice, but it requires first adding support for native file dialogs. This is quite a bit of work because file dialogs are handled differently on every platform. One option is to do a custom file dialog, but those usually turn out a bit janky and lack platform-specific niceties like user favorites.
