### ISSUE TITLE
Symbola has a non-free license

### ISSUE THREAD

**Issue by CyberTailor** [skyjake/lagrange#283]
It restricts commercial use (so it fails FSF and OSI criteria).

=> https://dn-works.com/ufas/

Unifont looks like abomination but covers all unicode characters and is licensed under OFL.

=> http://unifoundry.com/unifont/index.html

**Comment by skyjake** [comment]
Yes, this mistake should be rectified.

This ties into the previous font packaging issues like #195 and #273. One option is to distribute the fonts as a separate package, under a separate license, but even so I don't think Symbola can be included due to its license.

I'll look around for more OFL fonts... I can always mix and match characters from different fonts, if necessary.

**Comment by jobukkit** [comment]
Why not put Symbola in the Font Library, with a note about the license forbidding business and school usage? It still works well as a fallback for emoji's that Smol Emoji doesn't have yet (I tried OpenMoji-Black too, but it was rendered tiny).

P.S. I finished the Dutch translation!

**Comment by skyjake** [comment]
Unfortunately, [Symbola's license](https://dn-works.com/wp-content/uploads/2021/UFAS121921/License.pdf) prohibits me from doing that:
> USER ... may not ... in any way redistribute UFAS, with or without change

> P.S. I finished the Dutch translation!

Great! I'll be included in the next update. 👍
