### ISSUE TITLE
User-adjustable keyboard and mouse scrolling speeds

### ISSUE THREAD

**Issue by QuadrupleA** [skyjake/lagrange#297]
Smooth scrolling is a nice feature in Lagrange, but the timing seems ponderously slow - something like 700-1000ms of interpolation to scroll just a line or two with the up/down keys, makes interacting with it feel very tedious and unresponsive. It creates a lot of wasted time for the user too, having to wait 1sec or so for their scroll command to "complete". 

I would suggest 150-300ms (Chrome uses something like that) or at least provding a user-configurable preference (maybe presets -  Scrolling Speed: Fast / Medium / Slow).

**Comment by skyjake** [comment]
Adding a setting for this sounds like a good idea.

The current scrolling behavior is intended to allow comfortably keeping your eyes on the text while reading and scrolling simultaneously, while speeding up on repeated scrolls/mouse wheel events.

**Comment by QuadrupleA** [comment]
Thanks - I do see the velocity / momentum effect, that's nice for keeping your eyes on something. A user-selectable timing parameter with the current approach would probably do the trick.

**Comment by ghost** [comment]
Note that the scrolling by arrow keys *feels* significantly slower than scrolling by the mouse wheel, due to having to repeatedly press the arrow key over and over again.

What I would do is have two separate speeds, one for the mouse wheel and one for the arrow keys. And then make the arrow keys faster and/or scroll more at a time.

Currently, Scrolling by the mouse wheel is perfect, but scrolling by the arrow keys is not very good, imo.
