### ISSUE TITLE
Feature request: using ssh keys for client identity and server trust

### ISSUE THREAD

**Issue by sirnewton01** [skyjake/lagrange#305]
If have set up ssh keys to access a specific host then it would be great if Lagrange would use the same key when accessing that host, otherwise it could use my id_rsa key, if it's present. Similarly, if the host I'm connecting is not yet in the known_hosts file then Lagrange could add it and check if the key presented is different, reporting a warning.

**Comment by sirnewton01** [comment]
It appears that this is possible using the command line at least. https://security.stackexchange.com/questions/32768/converting-keys-between-openssl-and-openssh/32774#32774

**Comment by skyjake** [comment]
As discussed on the Gemini mailing list, the practical problem is that TLS requires the use of X.509 certificates, while SSH is using regular key pairs. In order for OpenSSL (or some other TLS library) to use the SSH keys, one will first need to create self-signed X.509 certificates using said keys.

When you create these certificates using your SSH keys, they are required to contain additional information such as subject and issuer names, and an expiration date. This information should be provided by the (human) owner of the keys, and it influences the certificate fingerprint that is used for server trust checks. In other words, there is no direct and unambiguous method for converting between SSH keys and TLS certificates without human intervention.

At this time I think this feature is outside of Lagrange's scope. It's better to do this kind of key/certificate conversion via external scripts, which will allow the generated certificates to also be used in other clients. We can reopen the issue if this turns out to be a popular thing to do.

**Comment by sirnewton01** [comment]
I think that Gemini clients should consider standardizing the identity and trust management across clients, like SSH, so that if a user switches between clients they are using the same identity and trust with sites that they visit. What I see is that each client is deciding on their own approach and ignoring the certificates of other clients, innovating in their own ways.

**Comment by skyjake** [comment]
I completely agree. At least on the desktop, it should be feasible to achieve a common storage convention for trusted server certificates and the user's client certificates. On other (mobile) platforms, one solution could be a common interchange format so clients can export/import certificates conveniently.

In practice, the details need to be hammered out as a collaboration between multiple client authors, taking into consideration things like safe storage of private keys.

As to an export/import file format, there are already pretty good ones available so it shouldn't be necessary to invent a new one. I believe [PKCS #12](https://en.wikipedia.org/wiki/PKCS_12) could work.

The big issue with .P12 is complexity, though. Reading and writing the data would have to happen via OpenSSL or other such library. A simpler way to go would be a password-protected ZIP archive containing the certs and keys in PEM format, for example.

**Comment by sirnewton01** [comment]
The next question is how to get other protocols on board so that users have a single multi-protocol, multi-client trust and identity management. I think that there's a desire to bring functionality to Gemini that belongs with other protocols in a multi-protocol world, but users are tempted to simplify their experience in areas like identity and trust. In my opinion that road leads to the astonishing feature creep of The Web over time.
