### ISSUE TITLE
Crash when loading manually edited bookmarks

### ISSUE THREAD

**Issue by Kodden585** [skyjake/lagrange#324]
Whenever I edit the bookmarks.txt file, which is the only way to remove or reorder bookmarks at the moment, Lagrange refuses to start up again afterwards.

```
[user@machine ~]$ lagrange
Lagrange: A Beautiful Gemini Client
[window] renderer: opengl (accelerated)
zsh: segmentation fault  lagrange
[user@machine ~]$ 
```

**Comment by skyjake** [comment]
> Whenever I edit the bookmarks.txt file

What kind of edits did you make in the file? Note that it has quite strict syntax requirements as described in section 3.5 of the Help page. You should also not insert any blank/unused lines in the file.

I will be replacing this bookmarks file with a new format in an upcoming release.

>  only way to remove bookmarks

There's a "Delete Bookmark" context menu item if you right-click on a bookmark in the sidebar.

> reorder bookmarks

The current version forces alphabetic ordering of bookmarks. I don't recommend changing the order inside bookmarks.txt, since it has no meaning at the moment.

**Comment by Kodden585** [comment]
I simply removed one of the bookmarks. Oh well, doesn't seem to matter much then if the format is going to be replaced soon anyway.

**Comment by skyjake** [comment]
My guess is that the bookmarks.txt parser doesn't ignore any empty lines at the end of the file correctly, causing a crash, but I haven't tested this in practice yet.

**Comment by skyjake** [comment]
Bookmarks were revamped in v1.7 so this issue has been resolved.
