### ISSUE TITLE
What is the Gemini protocol proxy

### ISSUE THREAD

**Issue by kowoba** [skyjake/lagrange#341]
After searching high and low for gemini protocol proxy server, I ended up here :)

This commit says "Added a Gemini proxy"

  https://github.com/skyjake/lagrange/commit/df0e00463c5b55f89471720c1bf4d83e1f428aae

but exactly what kind of Gemini proxy is supported?

I need a proxy for legacy IPv4-only clients to reach Gemini spaces over IPv6-only networks, same way for example Tinyproxy can proxy https....

https://tinyproxy.github.io

"Tinyproxy allows forwarding of HTTPS connections without modifying traffic in any way through the CONNECT method (see the ConnectPort directive"

Is this the type of proxy supported by lagrange? Or is there some gemini specific proxy around that I haven't found (it's hopeless to search, all hits are about gemini-web gateways, and not really proxies in my view.

Thanks!

**Comment by skyjake** [comment]
The Gemini proxy in this context is any Gemini server that responds to URLs at any domain and not just their own. If you configure one in Lagrange, the app sends all Gemini requests to the proxy instead of directly sending to the target host. The proxy server can then do whatever it wants with the given request.

I'm not aware of an existing IPv4-to-v6 proxy. I would imagine fully supporting client certificates would be tricky if not impossible, though.

**Comment by kowoba** [comment]
I see, so this is the kind of proxying described in section 2 here - https://gemini.circumlunar.space/docs/specification.gmi

This brings me back to my original quest - do you know of any gemini server software that actually implement this? :)

**Comment by skyjake** [comment]
> do you know of any gemini server software that actually implement this? :)

Sorry, I do not. However, I've only used [Agate](https://github.com/mbrubeck/agate) in any serious fashion, so I don't know if some of the servers listed on https://gemini.circumlunar.space/software/ have this feature.
