### ISSUE TITLE
Stop input prompts from reappearing when navigating history

### ISSUE THREAD

**Issue by kensanata** [skyjake/lagrange#382]
I'm not sure what the correct solution is, here. All I know is that often I want to go "back" and get shown a prompt again which I don't want to answer since I want to go even further back. So I hit "cancel" and then I'm free to hit "back" some more. Alternatively, have the back and forward buttons continue working even if the prompt is shown.

**Comment by skyjake** [comment]
There is already a mechanism that is used for redirected URLs (a "transient" flag) that affects how navigation works. I'll see if this can be applied to URLs whose response had a 1x status, maybe it'll solve the UX issue neatly.

If the input prompts are inlined (#127, #375) it should also make navigation less cumbersome.

**Comment by skyjake** [comment]
An additional detail: the underlying cause here is that only 2x responses are cached, so any other URL that one navigates back/forward to will trigger a new request; hence the input prompt reappearing. It could be better to cache the user's query string and show that as the cached copy  of the 1x page, perhaps.

**Comment by skyjake** [comment]
The behavior will be changed in v1.9. Navigation will skip the 1x status responses, so one can navigate back and forth to a query results page.
