### ISSUE TITLE
Translation of all-caps like SPECIAL TAGS

### ISSUE THREAD

**Issue by kensanata** [skyjake/lagrange#392]
I think these all caps texts are more like language keys and shouldn't be translated, correct? They shouldn't even show up in the weblate UI, I'd think.

**Comment by skyjake** [comment]
The all-caps style has been used for headings in the UI. I chose that because at the time there wasn't a bold font available. Now there is, though, so I'm thinking of switching them all to Title Case in the language strings. I can do the uppercasing programmatically if I still want to do that.

So yes, they all must be translated, but you don't have to keep them all-caps.

The actual string ID is shown as "Context" in Weblate.

**Comment by kensanata** [comment]
Hm, I see. Now I just need to find them all again. 😅

**Comment by kensanata** [comment]
OK, fixing it. :+1:
