### ISSUE TITLE
Add more Emoji characters in fonts distributed with the app

### ISSUE THREAD

**Issue by eshapard** [skyjake/lagrange#439]
Hey there, Just downloaded v1.10.1 and one of my icons that displayed in previous versions (1.4.1 seems to be displaying it just fine) does not display.

🦜 It's this nice little parrot here.

In v1.10.1, I tried downloading the fonts that previously came bundled with lagrange, and setting them as the body font one-by-one, but strangely that didn't fix it.

Using 'Nunito' as the body font on v1.4 displays the 🦜, but 'Nunito' on v1.10 doesn't.

Any ideas?

**Comment by skyjake** [comment]
Many of the Emoji characters came from the [Symbola font](https://dn-works.com/ufas/) but in Lagrange v1.5 it was removed due to the font's restrictive license (personal use only).

One solution to missing characters is to use system fonts (#195), but I've yet to start work on that. Another solution is to use different fonts, but unfortunately there doesn't seem to be a black & white Emoji vector font available anywhere. I've been slowly working on my own: [Smol Emoji](https://codeberg.org/skyjake/smol-emoji).

Newer versions of Symbola are available, but in OpenType format only. If one were to download it for their own personal use, one will still have to convert it to TrueType before it can be installed for use in Lagrange.

**Comment by eshapard** [comment]
Thanks skyjake! I just noticed the release notes for 1.5 mention the font issue. I'll look into symbola for personal use. :-)

**Comment by skyjake** [comment]
I wrote a little shell/Python script to help with this: https://git.skyjake.fi/gemini/font-library/src/branch/main/build/get_symbola.sh

**Comment by eshapard** [comment]
You're awesome, dude!

**Comment by skyjake** [comment]
v1.10.2 has a few more emoji, including this little guy:
<img width="231" alt="Screen Shot 2022-01-24 at 14 28 24" src="https://user-images.githubusercontent.com/1225742/150783037-4e82884b-294c-4e12-8d1d-375645fd37a9.png">

**Comment by eshapard** [comment]
Sweet! I'm a big fan of Lagrange! Thanks!

By the way, is there a technical reason why Lagrange is limited to black and white emojis, or was that just a style preference?

**Comment by skyjake** [comment]
It's a bit of both, although mostly technical. I'm using [stb_truetype](https://github.com/nothings/stb) to rasterize glyphs. It's a pretty amazing single-header library with no additional dependencies, which makes it perfect for Lagrange, but the downside is that it doesn't support color/bitmap glyphs or more advanced OpenType fonts. Personally I like monochrome vector fonts as they can be colored according to the overall page/UI theme and rendered in any resolution.

**Comment by skyjake** [comment]
Closing as this is more of a long-term project. Workarounds include installing the GNU Unifont (includes Unicode 14) from the Lagrange font library, and future system font rendering.

**Comment by skyjake** [comment]
There's a new Noto Emoji OFL font that's looking quite nice / mostly OK: 🎉 https://fonts.google.com/noto/specimen/Noto+Emoji/about

I'll bundle the new one to cover all Emoji up to Unicode 14, keeping the old fonts plus Smol Emoji as those glyphs have a nicer/familiar appearance.
