### ISSUE TITLE
ANSI background colours create vertical lines on preformatted text

### ISSUE THREAD

**Issue by xereeto** [skyjake/lagrange#466]
I love this browser! However, I noticed a small rendering glitch today when designing my own gemini capsule.

Specifically, preformatted text rendered with an ANSI background colour displays with vertical lines between the characters at the default zoom setting. This does not affect non-preformatted text, as you can see in the example below (top is normal, bottom is preformatted)

![image](https://user-images.githubusercontent.com/4806744/159100326-15ba2d57-8e94-4b21-9fa1-dd9560b6bef9.png)

The bug also appears to vanish if I zoom in or out, though it reappears at a couple of other zoom levels. Very strange.

This is on version 1.11.1.

edit: browsing aimlessly today i happened upon a site that uses block characters, and noticed the bug exists for those as well.
<img width="400" alt="image" src="https://user-images.githubusercontent.com/4806744/159106404-1a3cbaf5-ebe5-42cc-82f3-3e459070773a.png">

**Comment by skyjake** [comment]
I've fixed the problem with the backgrounds for v1.12.

As to the glyphs themselves, this is ultimately due to the text renderer not supporting hinting, which means the edges of the characters may end up on fractional pixel positions. The fonts are scaled to align their advance widths to the pixel grid, but that does not guarantee that the glyph's vertices aren't located somewhere between pixels. In short, it's not really fixable without switching to a different text renderer (e.g., FreeType).

**Comment by skyjake** [comment]
Closing since the issue with the backgrounds should be fixed now.
