### ISSUE TITLE
TLS session resuming broken on gem.sdf.org

### ISSUE THREAD

**Issue by h-bag** [skyjake/lagrange#479]
When I try to navigate to gemini://gem.sdf.org/hbag , or any other page hosted on gem.sdf.org, it doesn't load, which I've just attributed to their server not being the best. However, when I then try to just navigate to gem.sdf.org, that doesn't work either, despite working perfectly fine before I tried to navigate to one of the directories.

I originally thought this was also a problem with their server, but it seems nobody else is having this problem on different clients when I asked around.

**Comment by skyjake** [comment]
This looks like a server-side issue with resumed TLS sessions. You should be able to work around this by disabling Lagrange's "Resume TLS session" setting on gem.sdf.org. To find this setting, open any page on gem.sdf.org, click on the lock icon in the URL bar, and then click Settings in the info popup.

This is only the second server I've heard of having an issue with TLS session resuming. The issue with the first one was fixed by upgrading the server software. You may want to contact the gem.sdf.org admin(s) and let them know about this problem.

**Comment by h-bag** [comment]
When I do that, I just get "Connection refused", so...

I have made a post about it on the SDF bboard, however, but I don't remember the last time someone on there actually responded to one of my threads.

**Comment by skyjake** [comment]
Try again now? It was giving me connection refused errors a minute ago, too.

**Comment by h-bag** [comment]
Oh! It seems to be working now, thanks. I'll leave that TLS setting off.
