### ISSUE TITLE
Check if SSE4.1 is available at runtime

### ISSUE THREAD

**Issue by paper42** [skyjake/lagrange#501]
It would be nice for distributions if this could be detected at runtime, packages wouldn't have to disable SSE4.1 and people with newer CPUs would be able to benefit from it.

**Comment by skyjake** [comment]
There are basically two issues with this:

1. The use of the SSE intrinsics is pretty much exclusively done in inline functions. There is no clean demarcation that would allow switching it on or off at runtime.
2. The app is not math-heavy, so the benefits of SSE here are negligible.

Due to these reasons, it makes sense to just keep SSE disabled, as the time investment of adding runtime switching can't really be justified.
