### ISSUE TITLE
Display issue on Archlinux

### ISSUE THREAD

**Issue by DanielChesters** [skyjake/lagrange#566]
I am on an updated Archlinux with Gnome 43 and I have a display issue on Lagrange. 
The app UI is globally too big despite the UI scale factor set to 1. I have to set UI scale factor to 0.5 to have almost no so big UI size. Furthermore, I add a screenshot of the app with UI scale factor to 1.

![Lagrange on my machine](https://user-images.githubusercontent.com/291102/210877708-388cad8f-ef50-41c2-9f5a-0a92b99a0236.png)

I try stable and last git version from AUR, last version on Flatpak, AppImage version, and the last version from work/1.15 branch. Not only that, but I also try to reset my Lagrange config file.

**Comment by skyjake** [comment]
This usually happens because there's a problem detecting the correct monitor DPI value. Lagrange uses the [SDL library](https://libsdl.org) to do this. As a workaround, you could try setting the environment variable `LAGRANGE_OVERRIDE_DPI` before launching the app.

Not sure what DPI value would work for you, but you could try starting with `LAGRANGE_OVERRIDE_DPI=96` and adjust accordingly. Just remember to change the in-app UI scaling to back to 1.0.

**Comment by DanielChesters** [comment]
The environment variable `LAGRANGE_OVERRIDE_DPI` set to `96` work fine. 

Also, I try on another computer (with updated Archlinux, but with KDE plasma this time) and I have the issue without `LAGRANGE_OVERRIDE_DPI` too. For information, I use X11 on both machines.

**Comment by skyjake** [comment]
Closing this as there is not much to fix here. The workaround is to use aforementioned DPI override and/or UI scaling option.

Unfortunately, DPI detection is somewhat flaky on Linux and Lagrange relies on whatever information SDL is able to provide.
