### ISSUE TITLE
Home and End keys do not do anything in the client

### ISSUE THREAD

**Issue by alexlehm** [skyjake/lagrange#577]
Home and End keys in a browser scroll to top or bottom of the page, this is currently not doing anything in Lagrange

maybe you could please add that

**Comment by skyjake** [comment]
Have you checked out the "Keys" tab in Preferences? The first two are Jump to top/bottom. You could try binding them to your Home/End keys.

Due to some technical details with how [SDL](https://libsdl.org) handles key input, the default bindings may not actually apply to all physical keyboard layouts.

**Comment by alexlehm** [comment]
now it works without changing anything, I am not sure why it didn't before

thank you

I thought this might be an issue with the German keyboard, but it turns out it just works

**Comment by alexlehm** [comment]
I am not sure why I constantly run across issues that are not really issues and I only notice after creating a ticket
