### ISSUE TITLE
Lagrange does not complain about subdomain cert without wildcard

### ISSUE THREAD

**Issue by alexlehm** [skyjake/lagrange#582]
I am currently trying to get a gemini service working on a site called projectsegfautl (which i am not running, but I am a user)

the url is gemini://alexlehm.p.projectsegfau.lt/ which currently uses a cert p.projectsegfau.lt but not wildcard *.p.projectsegfau.lt and that does not cause an error or warning in Lagrange while it gives an error in other clients, e.g. Amfora and Bombadillo
I assume the site will fix their cert in the future, for now I think it should give a warning when accessing

![image](https://user-images.githubusercontent.com/156144/221864392-38c94d51-3c3a-4ca0-b663-83616115b912.png)

When I access the url with browser (which would not work but checks the cert), it gives the proper cert warning: https://alexlehm.p.projectsegfau.lt:1965/

**Comment by skyjake** [comment]
Implicit DNS wildcards is currently [intentional behavior](https://git.skyjake.fi/gemini/lagrange/src/commit/77bbc582ee721ec0e43c7eaa60f9967967f71b09/src/gmcerts.c#L529).

There has been some debate in the community about what are the practical security implications of TOFU, and I agree with the viewpoint that when it comes to self-signed certificates, the only truly meaningful data in the certificate are the encryption keys. The rest is unverified data that is essentially random strings provided by the creator of the certificate.

**Comment by alexlehm** [comment]
ok, i didn't know that

I will ask the admins what they have decided, if it is considered valid they can keep it like that
