### ISSUE TITLE
Opening Gempub in a tab messing up window layout

### ISSUE THREAD

**Issue by acidus99** [skyjake/lagrange#606]
I have 2 tabs open in Lagrange, as well as the side bar in outline mode. When I open an gempub, the layout of the windows gets all messed up. Here is a video of it happening:

![h4mNVR1Q6h](https://github.com/skyjake/lagrange/assets/4118560/270cfca6-d75a-413b-8ec8-cc2c9d6458d2)

I'm using Lagrange Version 1.16.5 (1.16.5) on macOS

**Comment by skyjake** [comment]
Yeah, that's not ideal. It is somewhat working as intended, with the main issue being that the leftmost sidebar should be closed automatically when opening the Gempub contents, because the left split is narrow.

However, a better way to support Gempubs would be to introduce an actual UI mode for them, not relying on split views. Some alternatives:
* Show the Gempub index page as the (or a) sidebar tab.
* Show the Gempub index as a dropdown menu/button mini-page.
* Show the Gempub index as a second column in the page margin.

Those kind of changes are scheduled for Lagrange v2.0, but in the meantime it wouldn't hurt to fix the sidebar behavior that's the main problem here.
