### ISSUE TITLE
README lists ENABLE_RESOURCE_EMBED option, but CMakeLists lack it

### ISSUE THREAD

**Issue by barracuda156** [skyjake/lagrange#609]
Was it forgotten or removed? I would be nice to have it working.

**Comment by barracuda156** [comment]
I am trying to make `lagrange` work on old macOS, building it Unix way, but it fails to find resources on launch:
```
36-25% /opt/local/bin/lagrange
Xlib:  extension "RANDR" missing on display "/tmp/launch-hZ8URc/:0".
failed to load resources: No such file or directory
```
Of course, `resources.lgr` are in fact installed (in `/opt/local/share/lagrange`), just the binary for w/e reason cannot see those.

**Comment by skyjake** [comment]
IIRC, embedding resources was removed when it become impractical due to several megabytes of fonts being distributed with the app. It became too unwieldy to both generate the source file with the embedded data and to compile it. There may exist methods to do the embedding more efficiently, however I also preferred to avoid adding further dependencies on external tools.

> on old macOS, building it Unix way, but it fails to find resources on launch:

I believe the macOS build assumes an application bundle is always in use, so it does not check the standard Unix locations. The locations are specified in the beginning of src/app.c, and the actual checked paths can be found around line 1120 in app.c. A new build option would have to be added to disable the application bundling, also affecting the paths checked when loading resources.lgr.

**Comment by barracuda156** [comment]
> I believe the macOS build assumes an application bundle is always in use, so it does not check the standard Unix locations. 

I was able to get around enforced bundling, I believe, and get `lagrange` installed, but launching fails due to missing resources. I will check the specific location you refer to and update here.

**Comment by skyjake** [comment]
I've now finally remembered to update the README, removing this obsolete option.

**Comment by barracuda156** [comment]
@skyjake Thank you. By the way, in principle would it work to make a local patch on our side to restore embedding into the current version? Or did something else change that would prevent this from working?

**Comment by skyjake** [comment]
Yes, there were other changes. The resources are now expected to come in a ZIP archive when they are loaded by resources.c. So after creating the resources.lgr (=zip), it would then have to be converted into a C source file and embedded as is. In the old version, the individual resources were embedded separately. Finally, `init_Resources()` would have to read from the embedded byte array instead of trying to load the ZIP archive from a file.
