### ISSUE TITLE
Buggy behavior for preformatted blocks

### ISSUE THREAD

**Issue by nervuri** [skyjake/lagrange#633]
I'm using Lagrange 1.17.0 on Debian 12 with the Sway window manager (Wayland).  I'm experiencing multiple issues with preformatted blocks.  Take, for example, the following page:

gemini://gemi.dev/gemini-mailing-list/000019.gmi

1. The first message is rendered with a smaller font than the following messages.
2. Folding and unfolding the first message repeatedly sometimes crashes Lagrange.  Sometimes it crashes for other reasons as well (example: switch to a different tab, then back, click the message => crash).
3. Sometimes clicking a folded message doesn't unfold it, only certain parts of the "text/plain"-labeled rectangle are clickable.

Or on this page:

gemini://gemi.dev/gemini-mailing-list/messages/000190.gmi

4. The folded message sometimes becomes a link to `gemini://gemi.dev/`.  This link doesn't open as usual, instead I get a pop-up asking if I'd like to open it in the default browser.  If I do, it opens in Amfora.
5. After folding and unfolding, only one of the lines in the message can be clicked to fold the message again.  The others are just selectable as normal text (on hover, the pointer changes to the text selection icon).

I've noticed issues 3 and 5 on `gemini://geminiprotocol.net/docs/gemtext.gmi` as well.

**Comment by skyjake** [comment]
1) This is intentional behavior, applied as a workaround since horizontal scrolling hasn't been implemented yet.

2) This sounds like issues with SDL's Wayland backend.

3) I haven't seen this myself. Could be a Wayland issue, I suppose, but the interactive part of preformatted blocks is currently not always as wide as one would expect.

4) This sounds very odd and I can't reproduce it.

5) This could be a bug and somewhat related to #629, although I haven't witnessed it myself.

I do plan to improve the way preformatted blocks work because the current implementation is a bit of a hack...

**Comment by skyjake** [comment]
Re: item 4: There is an assertion that fails there, which means I should be able to fix/improve the issue.

**Comment by skyjake** [comment]
Please test with v1.17.1 and report if any of these issues remain. General instability with Wayland is a separate problem.

**Comment by nervuri** [comment]
I tested for a couple of minutes and haven't encountered any of the five issues.  Seems like you fixed them, thanks!
