### ISSUE TITLE
Crash on ansi rendering (wrong text encoding)

### ISSUE THREAD

**Issue by michael-lazar** [skyjake/lagrange#639]
Langrage 1.17.4

Steps to repro:

1. Visit this URL: gemini://federal.cx/ansi/panther.txt
2. Lagrange crashes, MacOS system dialog says "Lagrange quit unexpectedly. Click reopen to..."

**Comment by skyjake** [comment]
There appears to be at least two problems with this page:

* The header declares the text encoding as utf-8, when it actually should be cp437. This likely leads to a failure to detect the escape sequences due to invalid UTF-8 sequences. 
* At least one of the lines assumes an 80-character-wide screen, as it lacks a newline at the end.

I could improve this a bit by verifying the correctness of the encoding and trying to re-detect it in case there are invalid sequences found.

**Comment by skyjake** [comment]
The fix is included in v1.17.5.
