### ISSUE TITLE
Gopher improved "i" support

### ISSUE THREAD

**Issue by ghost** [skyjake/lagrange#677]
Lagrange currently ignores "i" lines as invalid if they don't include a selector, host, and port. Considering how none of these make any sense for informative lines, lagrange should make them optional.
In other words:
"iThis is an informative line with no link\t\t\t"
should be accepted as a valid i line. I don't think the tabs should be optional as they're both part of the
spec and keeping them simplifies parsing, though some clients also support that.

**Comment by skyjake** [comment]
This makes sense. I applied the change for the upcoming v1.18, although I do not have a Gopher server immediately available for testing it.

**Comment by ghost** [comment]
This change adds the port number, but I was suggesting a specific exception for i lines. In their case the regex would be:
`(.)([^\t]*)\t([^\t]*)?\t([^\t]*)?\t([0-9]+)?`
Because the port number, selector, and host are all ignored for informative lines. In theory these could be kept general and defaulted to "localhost" "" and "70" but that may cause some unexpected behavior.

**Comment by zzo38** [comment]
I think the tabs should also be optional for the `i` item type; if any tabs are present then the first tab and everything that follows them on the same line should be ignored (since they are meaningless).

Whatever you think it should do, you should ensure that it won't crash if the data is malformed. (It also should be ensured to not crash if a line has a carriage return without a line feed or vice versa.)

My own gopher server does have some lines that have only one tab or no tabs. In the past there was also some lines in a menu, that lacked a carriage return (and someone's client crashed because of it), but I fixed that bug in my server since then (and hopefully the client they were using also was fixed).

**Comment by ghost** [comment]
I don't know the spec for "i" but my suggestion was to leave the tabs intact because the tabs are part of what the gopher spec says a line is. It's a bit of an annoying gotcha to figure out at first but it keeps the protocol and clients more consistent.

**Comment by skyjake** [comment]
I agree with @tekktonic. Even though `i` is a non-canonical line type, every line type in a gophermap should have the same general syntax.

Disclaimer: I have no idea how `i` is actually used in the wild, and that would be what matters with community conventions...

When it comes to avoiding crashes, Lagrange tries to be careful to ignore anything that it doesn't recognize.
