### ISSUE TITLE
flatpak version not working? 

### ISSUE THREAD

**Issue by rebeltaz** [skyjake/lagrange#682]
I installed Lagrange via flatpak (version 1.17.6) and tried running it through the gui Applications menu. Nothing ever came up, although it does show up under System Monitor's Processes. So I tried running it with "flatpak run fi.skyjake.Lagrange" on the command line. That gave me the line "Lagrange: A Beautiful Gemini Client" and dropped the cursor to the next line. That was it. I have to CTRL-C to kill it, but the window never comes up. I downloaded the appimage and that seems to work fine. 

I ma running Ubuntu 22.04, but I have gnome-flashback installed, if that makes a difference. 

Thanks.

**Comment by skyjake** [comment]
Any change with 1.18 via Flatpak?

Sometimes a missing window is caused by the window coordinates being outside the screen area. This might happen when one switches between single and multi-monitor setups. The window coordinates are saved in the prefs.cfg file under .config/lagrange/. IIRC, flatpak has its own .config directory somewhere for the apps.

**Comment by rebeltaz** [comment]
It does! That works (the new version). Thank you!
