### ISSUE TITLE
Compounded emoji are displayed as components

### ISSUE THREAD

**Issue by emceeaich** [skyjake/lagrange#81]
When displaying a .gmi file with emoji which are compositions, such as 👩‍🚀, the emoji is displayed as 👩[zwd]🚀.

Environment: Ubuntu
Version: 0.11.0

**Comment by skyjake** [comment]
The reason why this occurs is because Lagrange uses a custom text renderer and a custom set of fonts. The renderer currently does not recognize Emoji compositions. Also, the fonts don't contain all the latest Emojis, particularly when it comes to the composited ones.

One possible solution would be to fall back to the system-provided fonts for a more complete set of glyphs.
