### ISSUE TITLE
Misaligned unicode box lines

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#82]
Hello,

On my test games which use unicode box characters to draw boards, the lines are discontinued and misaligned in lagrange, while they work fine in other browsers.

gemini://chess.lanterne.chilliet.eu

gemini://tictactoe.lanterne.chilliet.eu

**Comment by skyjake** [comment]
Just needed a minor tweak to the text renderer. It was trying to be clever when mixing glyphs from different fonts, but in this case the font didn't change AFAICS.

**Comment by MCMic** [comment]
Now they are aligned, but still discontinued, which is not the case in other clients.
![lagrange-chess](https://user-images.githubusercontent.com/106382/101241867-3e4eaf00-36fa-11eb-926d-236867c09236.png)

Same site with kristall:
![kristall-chess](https://user-images.githubusercontent.com/106382/101241899-7e159680-36fa-11eb-83e5-cca4e83259be.png)

**Comment by MCMic** [comment]
Actually it looks a bit misaligned in kristall.

In lagrange it also seem to vary with zoom setting.

**Comment by MCMic** [comment]
In Ariane on my phone it’s perfect, but maybe the problem is in the font installed on my computer?

**Comment by skyjake** [comment]
Lagrange's problem is at least that there are some issues with the font metrics vs. the box-drawing glyphs, which are supposed to be exactly as tall as the line spacing. Horizontally, there could be an off-by-one issue with the glyph subpixel positioning, or maybe it's because the glyphs are drawn unhinted. I'll need to see if there are some tweaks to be made.

Falling back to system-provided font rendering is one way to fix this, but of course means adding platform-dependent code.

These artifacts are less noticeable on a HiDPI display, or when scaling the text larger.

Another site where glyph overlaps can be seen is gemini://tilde.team/~sumpygump/explore/

**Comment by skyjake** [comment]
I added this new issue: #86

**Comment by skyjake** [comment]
Made some tweaks that fixed most of the discontinuations (#86).
