### ISSUE TITLE
Unicode rendering: Emojis vs. monospacing

### ISSUE THREAD

**Issue by MCMic** [skyjake/lagrange#98]
Hello,

Visiting gemini://gem.vectorpoem.com/projects_log/2020-12-06.gmi with lagrange does not look right.

As usual, I can’t be sure if this is a lagrange issue or something to do with the fonts installed on my system or something.

**Comment by skyjake** [comment]
Lagrange does not use fonts installed on your system (at the moment, at least).

The problem here is that preformatted blocks are considered by Lagrange to be strictly monospaced. However, the Fira Mono font used for monospaced text does not have all the Unicode glyphs, and the missing ones are taken from the non-monospace Symbola. Those can be much wider than the monospacing has room for, and thus they overlap like on gem.vectorpoem.com.

The options here are:

- (Currently implemented:) Center the glyphs in the available space, so at least they work in tables, etc. like on gemini://chess.lanterne.chilliet.eu.
- Find a monospaced font with better glyph coverage. I'm not super happy with Fira Mono, so I'll look around if there is one.
- I could force-fit the glyphs in the available space, but that could make them illegible/weirdly squished.
- Don't enforce monospacing so strictly, at the cost of misaligning some Unicode art.

**Comment by MCMic** [comment]
Ok, this is consistent with what I’m seeing.

I think it’s important that monospace stays monospaced.
So, not sure there is a good solution besides finding a more complete font. In the Tic Tac Toe I ended up not using ❌ and ⭕, which are the unicode chars for this, because on a lot of clients they would be wider than the box drawing chars.

**Comment by skyjake** [comment]
Oops, got the issue reference wrong. ef07b24ad3431496372d3cfd2884b0609b940e27 addresses this issue.

**Comment by skyjake** [comment]
I ended up with a mixed solution. There's a new monospace font (Iosevka) and Emoji spacing is a bit relaxed in otherwise monospaced text. This prevents them overlapping each other. However, the original monospacing is restored when whitespace permits.

> ❌ and ⭕

The Tic Tac Toe grid will render correctly with these changes, as the whitespace following ❌ and ⭕ allows the grid lines to be placed using the default monospacing.

> gem.vectorpoem.com

This still won't render as the author intended (and it was intended for colored Emojis anyway), but it's less messy without overlapping characters.
